[general]
import = ["~/.config/alacritty/pippo.toml"]

[colors.cursor]
cursor = "#fc0fc0"
text = "#000000"

[cursor]
blink_interval = 400

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 16.0

[font.bold]
family = "CaskaydiaCove Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Propo"

[font.italic]
family = "CaskaydiaCove Nerd Font Propo"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Propo"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
decorations = "Full"
opacity = 0.8

[window.padding]
x = 8
y = 8

[env]
WINIT_X11_SCALE_FACTOR = "1"
