# Colors (Hyper)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#F81CE5'
cursor = '#dddddd'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#bb0000'
green   = '#00875f'
yellow  = '#feff00'
blue    = '#021aff'
magenta = '#cc00ff'
cyan    = '#00875f'
white   = '#d0d0d0'

# Bright colors
[colors.bright]
black   = '#888888'
red     = '#fe0100'
green   = '#00875f'
yellow  = '#feff00'
blue    = '#021aff'
magenta = '#cc00ff'
cyan    = '#00875f'
white   = '#d0d0d0'
